version: "3.9"
services:
  grpcserver:
    build: ./server
    ports:
      - "50052:50051"
    networks:
      - grpctuiter

  grpcclient:
    build: ./cliente
    environment:
      - CLIENT_HOST=:5000
      - SERVER_HOST=grpcserver:50051
      - NAME=instanciagrpc
    ports:
      - "5000:5000"
    networks:
      - grpctuiter

networks:
  grpctuiter:
    driver: "bridge"